name: Test and Deploy Preprod to Heroku
on:
  push:
    branches:
      - preprod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Init project
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@master

      - name: Install Packages
        run: sudo npm ci

      - name: Run ESLint
        run: sudo npm run lint

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_PREPROD}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
